# Generated by Django 2.2.1 on 2019-07-07 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('received_on', models.DateField(auto_now_add=True)),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('state', models.CharField(choices=[('PD', 'Pending'), ('AC', 'Accepted'), ('IP', 'In Progress'), ('CL', 'In Clarification'), ('FI', 'Finished'), ('XX', 'Rejected')], default='PD', max_length=2)),
                ('firstname', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('appartement', models.CharField(max_length=12)),
                ('estinated_number_of_people', models.IntegerField()),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='RentalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Rental')),
            ],
        ),
    ]
