# Generated by Django 2.1.4 on 2019-07-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='facility',
            field=models.CharField(choices=[('TR', 'Tea Room'), ('BA', 'Bar'), ('BO', 'Boat'), ('GY', 'Sportshall'), ('GA', 'Games'), ('WS', 'Workshop Tools')], default='TR', max_length=2),
        ),
    ]
