# Generated by Django 2.1.4 on 2019-07-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rental_facility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='tenant',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='rental',
            name='surname',
            field=models.CharField(default='Dharod', max_length=64),
            preserve_default=False,
        ),
    ]
