# Generated by Django 2.2.1 on 2019-07-09 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_facility_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rental.Facility'),
        ),
    ]
