# Generated by Django 2.2.1 on 2019-07-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20190702_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
