# Generated by Django 2.2.1 on 2019-07-04 22:44

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20190703_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='slug',
            field=models.SlugField(default=uuid.uuid4(), unique=True),
            preserve_default=False,
        ),
    ]
