# Generated by Django 2.2.7 on 2020-02-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_auto_20200113_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='appartement',
            new_name='apartement',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='estinated_number_of_people',
            new_name='estimated_number_of_people',
        ),
    ]
