# Generated by Django 2.2.7 on 2020-01-13 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_rental_responsiblemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalactivity',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
